name: Continuous Integration

on:
  pull_request:
    branches:
      - master
jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run test
        env:
          CI: true
          HOST: localhost
          PORT: 5000
